# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1c83fe41-19ce-431b-adb9-decc77cf0a42";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-3f25cd59-6189-473b-9c3a-a1dcf596d944".device = "/dev/disk/by-uuid/3f25cd59-6189-473b-9c3a-a1dcf596d944";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/0E6D-B4C0";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/36233c30-f122-46a8-b102-b1a6d6d61991";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-5dcee301-7bfb-4987-8807-db796ba10b00".device = "/dev/disk/by-uuid/5dcee301-7bfb-4987-8807-db796ba10b00";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4263931a-9c24-40cc-959c-88f64b0028d1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
